### ISSUE TITLE
UNIXServer LoadError when running minitest_bisect on windows

### ISSUE THREAD

**Issue by pgundlupetvenkatesh** [minitest/minitest-bisect#24]
I am getting the below UNIXServer LoadError when I run minitest_bisect on Windows 10
```
$ minitest_bisect --seed 3377 spec/examples/test_file_spec.rb
<path>/Ruby26-x64/lib/ruby/2.6.0/drb/unix.rb:6:in `<top (required)>': UNIXServer is required (LoadError)
        from <path>/Ruby26-x64/lib/ruby/site_ruby/2.6.0/rubygems/core_ext/kernel_require.rb:85:in `require'
        from <path>/Ruby26-x64/lib/ruby/site_ruby/2.6.0/rubygems/core_ext/kernel_require.rb:85:in `require'
        from <path>/Ruby26-x64/lib/ruby/2.6.0/drb/drb.rb:804:in `auto_load'
        from <path>/Ruby26-x64/lib/ruby/2.6.0/drb/drb.rb:772:in `open_server'
        from <path>/Ruby26-x64/lib/ruby/2.6.0/drb/drb.rb:1403:in `initialize'
        from <path>/Ruby26-x64/lib/ruby/2.6.0/drb/drb.rb:1715:in `new'
        from <path>/Ruby26-x64/lib/ruby/2.6.0/drb/drb.rb:1715:in `start_service'
        from <path>/Ruby26-x64/lib/ruby/gems/2.6.0/gems/minitest-server-1.0.6/lib/minitest/server.rb:15:in `run'
        from <path>/Ruby26-x64/lib/ruby/gems/2.6.0/gems/minitest-bisect-1.5.1/lib/minitest/bisect.rb:77:in `run'
        from <path>/Ruby26-x64/lib/ruby/gems/2.6.0/gems/minitest-bisect-1.5.1/lib/minitest/bisect.rb:58:in `run'
        from <path>/Ruby26-x64/lib/ruby/gems/2.6.0/gems/minitest-bisect-1.5.1/bin/minitest_bisect:5:in `<top (required)>'
        from <path>/Ruby26-x64/bin/minitest_bisect:27:in `load'
        from <path>/Ruby26-x64/bin/minitest_bisect:27:in `<main>'
```
Added `require 'minitest/bisect'` in spec_helper.rb
I usually run unit test suite by `bundle exec rake` command and individual spec by `bundle exec ruby spec/examples/test_file_spec.rb`

Gem versions -
minitest v5.15.0
minitest-bisect v1.5.1
minitest-hooks v1.5.0
minitest-reporters v1.5.0
minitest-spec-context v0.0.4

My gemfile.lock
```
GEM
  remote: https://rubygems.org/
  specs:
    addressable (2.8.0)
      public_suffix (>= 2.0.2, < 5.0)
    akami (1.3.1)
      gyoku (>= 0.4.0)
      nokogiri
    ansi (1.5.0)
    awesome_print (1.9.2)
    builder (3.2.4)
    byebug (11.1.3)
    coderay (1.1.3)
    gyoku (1.3.1)
      builder (>= 2.1.2)
    httpi (2.5.0)
      rack
      socksify
    method_source (1.0.0)
    minitest (5.15.0)
    minitest-bisect (1.5.1)
      minitest-server (~> 1.0)
      path_expander (~> 1.1)
    minitest-hooks (1.5.0)
      minitest (> 5.3)
    minitest-reporters (1.5.0)
      ansi
      builder
      minitest (>= 5.0)
      ruby-progressbar
    minitest-server (1.0.6)
      minitest (~> 5.0)
    minitest-spec-context (0.0.4)
    nokogiri (1.13.1-x64-mingw32)
      racc (~> 1.4)
    nori (2.6.0)
    path_expander (1.1.0)
    pry (0.13.1)
      coderay (~> 1.1)
      method_source (~> 1.0)
    pry-awesome_print (9.6.11)
      awesome_print (>= 1.1.0, < 999)
      pry (>= 0.9.0, < 999)
    pry-byebug (3.9.0)
      byebug (~> 11.0)
      pry (~> 0.13.0)
    public_suffix (4.0.6)
    racc (1.6.0)
    rack (2.2.3)
    rake (12.3.3)
    ruby-oci8 (2.2.10-x64-mingw32)
    ruby-progressbar (1.11.0)
    socksify (1.7.1)
    titleize (1.4.1)
    wannabe_bool (0.7.1)
    wasabi (3.7.0)
      addressable
      httpi (~> 2.0)
      nokogiri (>= 1.4.2)
    webrick (1.7.0)
    win32console (1.3.2)
    yard (0.9.27)
      webrick (~> 1.7.0)

PLATFORMS
  x64-mingw32

DEPENDENCIES
  bundler (~> 2.0)
  minitest (~> 5.0)
  minitest-bisect (~> 1.5.1)
  minitest-hooks (~> 1.5.0)
  minitest-reporters (~> 1.5)
  minitest-spec-context (~> 0.0.4)
  pry-awesome_print (~> 9.6, >= 9.6.0)
  pry-byebug (~> 3.5, >= 3.5.0)
  rake (~> 12.0, >= 12.0.0)
  win32console (~> 1.3.2)
  yard (~> 0.9)

BUNDLED WITH
   2.2.32
```

**Comment by zenspider** [comment]
Yup. This is the way it is written. I don't/won't use windows so supporting it is out of scope for me.

**Comment by pgundlupetvenkatesh** [comment]
Okay thanks for checking it out.
